config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  post 'sales' => 'sales#create'
  get 'sales/done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :cod, uniqueness: true
  validates :detail, presence: true
  validates :category, inclusion: { in: %w(uno dos tres cuatro cinco), message: "%{value} no es una categoría válida" }
  validates :value, numericality: true
  validates :discount, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    if params[:sale][:tax] == '1'
      @sale.total = (@sale.value - @sale.discount) * 1.19
      @sale.tax = 19
    else
      @sale.total = @sale.value - @sale.discount
      @sale.tax = 0
    end
    if @sale.save
      redirect_to sales_done_path
    else
      render :new
    end
  end

  def done
    @sales = Sale.all
  end

  private
  def sale_params
    params.require(:sale).permit(:cod, :detail, :category, :value, :discount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registro de Ventas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://bootswatch.com/3/cyborg/bootstrap.min.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/sales/done.html.erb
<h1>El registro fue almacenado con éxito!</h1>
<table class="table">
  <thead>
    <tr>
      <th>Cod</th>
      <th>Detail</th>
      <th>Category</th>
      <th>Value</th>
      <th>Discount</th>
      <th>Tax</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
  <% @sales.each do |sale| %>
    <tr>
      <td><%= sale.cod %></td>
      <td><%= sale.detail %></td>
      <td><%= sale.category %></td>
      <td><%= sale.value %></td>
      <td><%= sale.discount %></td>
      <td><%= sale.tax %></td>
      <td><%= sale.total %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Volver', sales_new_path, class: 'btn btn-primary' %>

app/views/sales/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Ingresar venta</h1>
    <%= form_with model: @sale do |f| %>
      <div class="form-group">
        <%= f.label :cod %>
        <%= f.text_field :cod, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :detail %>
        <%= f.text_area :detail, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :category %>
        <%= f.text_field :category, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :value %>
        <%= f.number_field :value, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :discount %>
        <%= f.number_field :discount, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :tax %>
        <%= f.check_box :tax %>
      </div>
      <%= f.submit 'Ingresar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>